services:
  app:
    image: ghcr.io/ihavedizziness/server-fastapi:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
