apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stats-server
  namespace: stats-server
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stats-server
                port:
                  number: 80
